server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/remittance}
    username: ${SPRING_DATASOURCE_USERNAME:remittance}
    password: ${SPRING_DATASOURCE_PASSWORD:remittance}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: info
    org.springframework.web: info
